### ISSUE TITLE
Invalid Syntax?

### ISSUE THREAD

**Issue by Matias-source** [thanks4opensource/NotLinuxAjazzAK33RGB#3]
`raise ValueError,   "version mismatch, file: %s  code: %s" \
                    ^
SyntaxError: invalid syntax`

I tried to run the program but i have this error

**Comment by thanks4opensource** [comment]
@Matias-source: Are you using the "-f" or "--file" command line option? Search for "--file" in the README on the main project page. Also see [Older Firmware --- WARNING! ](https://github.com/thanks4opensource/NotLinuxAjazzAK33RGB#older_firmware). Do you have a line with "version	0 1 0" in the file? See [File Format (--file option) and Syntax ](https://github.com/thanks4opensource/NotLinuxAjazzAK33RGB#file-format---file-option-and-syntax-). Also see line number 3 ("version 0 1 0") of the example file https://github.com/thanks4opensource/NotLinuxAjazzAK33RGB/blob/master/mmo.leds .  Have you modified line number 41 ("VERSION = (0, 1, 0)") in your copy of  https://github.com/thanks4opensource/NotLinuxAjazzAK33RGB/blob/master/ajazz.py ? Also, ajazz.py was written using Python 2.x -- are you using Python 3.x?

**Comment by thanks4opensource** [comment]
@Matias-source: Your problem is likely that you are using Python 3 instead of Python 2. Change the first line of https://github.com/thanks4opensource/NotLinuxAjazzAK33RGB/blob/master/ajazz.py from `#!/usr/bin/env python`to `"#!/usr/bin/env python2`". If you do not have Python 2 on your system, you can modify the code for Python 3 by changing all occurrences of `raise SomeError, ...` to `raise SomeError(...)`. Hovever, there may be other Python 3 incompatibilities in the program.

**Comment by Matias-source** [comment]
Thanks you!
